In [7]:
import numpy as np

In [8]:
# Creating a matrix
matrix_1 = np.array([[2,3],[6,7]])
matrix_1

array([[2, 3],
       [6, 7]])

In [9]:
# num rows, num columns
matrix_1.shape

(2, 2)

In [10]:
matrix_2 = np.array([[10,35,45],[50,64,80],[20,15,90]])
matrix_2

array([[10, 35, 45],
       [50, 64, 80],
       [20, 15, 90]])

In [11]:
matrix_2.shape

(3, 3)

# Random Matrix

In [12]:
rand = np.random.rand(5,5)
rand

array([[0.39331051, 0.62581142, 0.30269089, 0.32949548, 0.13808346],
       [0.62935171, 0.40050781, 0.2817328 , 0.17009051, 0.42767246],
       [0.77071699, 0.12921918, 0.94758888, 0.70435657, 0.19192536],
       [0.24317726, 0.87785415, 0.17399435, 0.48661131, 0.76098087],
       [0.7571334 , 0.93503922, 0.34980066, 0.68622106, 0.27749339]])

In [13]:
rand2 = np.random.randint(100, size = (3,3))
rand2

array([[18, 88, 32],
       [91, 29, 34],
       [68, 20, 87]], dtype=int32)

# Special Matrices

In [ ]:
# All values = 1
matrix_3 = np.ones((2,3))
matrix_3

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
# Zero Matrix
matrix_4 = np.zeros((3,3))
matrix_4

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
# Identity Matrix
matrix_5 = np.eye(4)
matrix_5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
# transpose
matrix_6 = np.transpose(rand2)
matrix_6

array([[18, 91, 68],
       [88, 29, 20],
       [32, 34, 87]], dtype=int32)

# Matrix Operations

In [20]:
A = np.array([[2,3], [4,5]])
A

array([[2, 3],
       [4, 5]])

In [22]:
B = np.array([[6,7], [8,9]])
B

array([[6, 7],
       [8, 9]])

## Adding 2 Matrices

In [23]:
sum = A + B
sum

array([[ 8, 10],
       [12, 14]])

In [24]:
sum2 = np.add(A, B)
sum2

array([[ 8, 10],
       [12, 14]])

## Matrix Subtraction

In [25]:
sub = A - B
sub

array([[-4, -4],
       [-4, -4]])

In [26]:
sub2 = np.subtract(A, B)
sub2

array([[-4, -4],
       [-4, -4]])

## Multiplying by a Scalar

In [27]:
sc = 5 * A
sc

array([[10, 15],
       [20, 25]])

In [28]:
sc2 = np.multiply(5, A)
sc2

array([[10, 15],
       [20, 25]])

## Multiply 2 Matrices

In [29]:
prod = A * B 
prod

array([[12, 21],
       [32, 45]])

In [30]:
prod2 = np.multiply(A, B)
prod2

array([[12, 21],
       [32, 45]])